---
title: ""
---

### ARTICLE I. NAME 

The name of this Interest Group is Statistics and Pharmacometrics (SxP), herein after referred to as the Interest Group.

### ARTICLE II. SCOPE 

The objectives of the Interest Group are to

1\. Promote collaboration between Statisticians and Pharmacometricians by

1.  Providing a forum for ongoing communication between statisticians and pharmacometricians about their respective disciplines including methodology and terminology.

2.  Championing the utility of pharmacometric modeling.

3.  Advocating good statistical practices.

4.  Providing educational opportunities.

5.  Facilitating discussions between the two groups for how each interprets their own roles; explain how each other thinks and why.

2\. Encourage statisticians to seek careers in Pharmacometrics. Encourage academic institutions to introduce pharmacometric topics in bio-statistics programs and increase the emphasis on understanding of fundamental statistical principles in pharmacometric programs.

3\. Bridge the gap between Pharmacometricians publishing statistical methodology in Pharmacometrics journals with similar methodology published in statistical journals. Increase the coverage of pharmacometric-related statistical topics and pharmacometric applications in statistical journals.

4\. Provide new forums or take advantage of existing forums for initiating scientific discourse.

### ARTICLE III. MEMBERSHIP 

Membership in the Interest Group shall include anyone interested in establishing collaborations between statisticians and pharmacometricians. Membership in ASA or ISoP is not required. There are no dues.

### ARTICLE IV. MEETINGS 

The twice annual business meetings of the Interest Group shall be held in connection with the annual Joint Statistical Meetings and the American Conference on Pharmacometrics and shall be announced in advance, preferably in the printed program for each meeting. Approximately monthly meetings of the Steering Committee will also be scheduled. Business may also be conducted with the Interest Group members by mail and/or email.

### ARTICLE V. OFFICERS 

The Interest Group is led by a Steering Committee with two co-Chairs.  The Steering Committee is elected by the Membership, and from the Steering Committee the co-Chairs are selected, as described in this section. 

The Steering Committee is charged with providing support, advocacy, and enablement for the projects conducted by the Interest Group.  Members of the Steering Committee sponsor and lead Working Groups to accomplish the goals of the Interest Group. Steering Committee members are elected to 3-year terms.  Members of the Interest Group may serve repeated terms on the Steering Committee, but are limited to 2 consecutive terms.  The Steering Committee shall consist of at least four self-identified statisticians, four self-identified pharmacometricians and two programmers. Consideration should be given to having representatives from academia, global regulatory agencies, and industry on the Steering Committee.

The co-Chairs are the primary contacts for the Steering Committee and are responsible for representing the Interest Group with the sponsoring organizations. The co-Chairs facilitate the meetings of the Steering Committee.  One co-Chair will be a member of and represent ASA, and one co-Chair will be a member of and represent ISoP. Each co-Chair will serve a two-year term. For continuity, co-Chair terms will be staggered with the ASA co-Chair's term starting in odd years and the ISoP co-Chair's term starting in even years. Co-Chairs should be selected from among the Steering Committee members. Nominations for the next co-Chair will be solicited from the Steering Committee in October and the Steering Committee will vote on the co-Chair in November. Terms will start in February.  Note: if necessary, a co-chair may serve beyond the intended 3-year term to conclude their duties as co-chair.

The co-Chair rotating off the Steering committee, plus any other Steering Committee members ending their term, shall form the Nominating Committee for filling upcoming vacancies. The outgoing co-Chair shall organize the Nominating Committee in October. They will solicit a call for nominations from the broader membership group, as well as from specific regulatory agencies. Final nomination recommendations are approved by the Steering Committee and put to a vote by the membership for pharmacometric positions, statistician positions, and programming positions.  Voting will be held electronically (such as through email or using an online survey/voting tool), and open to the members registered on the Interest Group email distribution list at the time of the vote. 

In addition, there will be up to three at-large positions on the Steering Committee recruited by the co-Chairs for the purpose of balancing representation across regulatory, academia, and industry as well as pharmacometricians and statisticians.

Steering committee members who need to leave before completion of their term will be replaced by appointments chosen by the co-chairs. The term of appointed steering committee will last only until the next voting cycle.

Workstreams include the following:

1.  Technical topics, best practices, and education

2.  Outreach and web content

3.  PKPD Programming Forum

### ARTICLE VIII. AMENDMENTS 

The charter is reviewed annually at the beginning of the year by the Steering Committee. Changes to the charter may be proposed at any time. The Steering Committee shall vote on any proposed changes to the charter. Changes will be approved if a majority of the Steering Committee, including not fewer than half of its statistical members and not fewer than half of its pharmacometric members vote in favor of the changes. 
