---
title: "Conference Content"
---

-   [American Conference of Pharmacometrics (ACoP)](https://www.go-acop.org/default.asp?id=46&keuze=meeting)

-   [Population Approach Group Europe (PAGE) meeting](https://www.page-meeting.org/default.asp?keuze=search) Link to all abstracts from 1992 to 2022

-   [World Conference on Pharmacometrics (WCoP)](https://go-wcop.org/)

#### The ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop (2024):

-   [Partnerships among quantitative sciences to optimize drug development](../files/ASAFCS2024.pdf){target="_blank"}
-   [Statistical and Pharmacometric Analysis Using Estimand Framework: A Case Study](../files/ASA2024PresentationJafarFinal.pdf){target="_blank"}
-   [Model Informed Drug Development (MIDD): Opportunities for Collaboration](../files/OBOCP_OpportunitiesCollaboration_202409.pdf){target="_blank"}
-   [Informing study designs at decision points through data and modeling driven approaches](../files/Decision-points-through-data.pdf){target="_blank"}
