---
title: "ACoP16 Posters"
description: SxP reviewed the ACoP program and abstracts to select content of interest for SxP
categories: 
- ACoP15
- Posters
date: 2025-10-18
toc: true
---

[Link to the ACoP16 program and abstracts](https://acop2025.eventscribe.net/PosterTitles.asp?pfp=BrowsebyTitle)

## Sunday Oct 19

- **(S-010)**
    - Bayesian modeling allows early inference of pharmacokinetic/pharmacodynamic relationship for a novel small molecule STING agonist in Phase I
- **(S-014)**
    - Survival Modeling of Dementia Risk Using Metabolic Syndrome-Related Genetic Variants
- **(S-015)**
    - Improving Physical Activity Classification with Free-living Wrist Sensor Data: Diving into Unique Feature Groups
- **(S-039)**
    - Machine Learning and Mechanistic Modeling to Predict Intravenous Pharmacokinetic Profiles in Humans
- **(S-046)**
    - Assessment of Weight Loss by Amylin Receptor Agonists Alone and In Combination with GLP-1 Receptor Agonists: A Model-Based Meta-Analysis
- **(S-054)**
    - Computer Modeling of Bevacizumab Drug Distribution After Intravitreal Injection in Rabbit and Human Eyes
- **(S-108)**
    - Impact of Misspecified Residual Error Model for Heavy-Tailed Error Distribution on PK Model Parameter Estimates
- **(S-114)**
    - A Bayesian Population Pharmacokinetic Analysis of Oritavancin in Pediatric Patients with Skin Infections
- **(S-116)**
    - A Novel Bayesian Adaptive Design for Phase I Dose Escalation with Improved Efficiency and Accuracy in Estimation of Maximum Tolerated Dose

## Monday October 20

- **(M-004)**
    - Optimal Sampling Workflows with NMsim and NONMEM
- **(M-023)**
    - Towards uncertainty assessment-based acceptability thresholds for model validation?
- **(M-078)**
    - Combining Mechanistic Modeling and Deep Learning for Predicting Survival Probabilities in Oncology
- **(M-083)**
    - Disease progression simulation via generative AI: assessing the credibility of a conditional longitudinal autoencoder via a case study in Alzheimer’s Disease

## Tuesday October 21

- **(T-039)**
    - Predicting Tumor Growth Dynamics and Overall Survival with Deep Learning Model
- **(T-068)**
    - Model selection for precision dosing: Comparison of Machine Learning and Evidence-plus-Expertise Algorithms
- **(T-069)**
    - Simplifying the Communication of Covariate Effects from Pharmacometric Models - The Role of Unconditional Covariate Effects



## Tuesday Nov 12

- **(T-016)** 
    - Bridging the Gap: A Comprehensive Checklist for Hybrid Pharmacometrics-Machine Learning Model Building to Support Oncology Clinical Development [_AI/ML_]
- **(T-024)** 
    - A Bayesian Approach to Item Response Theory Modeling for Exposure-Response Relationships in Stan [_Bayesian Statistics_]
- **(T-042)** 
    - Use of Model-informed Drug Development and Natural History Data to Inform the Development of Iluzanebart in ALSP: A Neurological Rare Disease [_MIDD_]
- **(T-056)** 
    - A modified Bayesian information criterion (mBIC) with multiple testing correction for population pharmacokinetic model building [_Statistical methodology_]
- **(T-057)** 
    - Hybrid Population PK-Machine Learning Model Approach to Predict Infliximab Concentrations in Pediatric Patients with Crohn's Disease [_AI/ML_]
- **(T-075)** 
    - Enhancing Parameter Estimation Process for Pharmacokinetic-Pharmacodynamic Models with Meta-heuristic Optimization Approaches [_Statistical methodology_]
- **(T-078)** 
    - A Bayesian Semi-Mechanistic Dose-Finding Design for Phase I Drug Combination Trials in Oncology [_Bayesian statistics_]
- **(T-091)** 
    - Fast Stepwise Selection Methods for Efficient Covariate Model Development in Population Data Analysis [_Statistical methodology_]
- **(T-135)** 
    - Potential Bias Evaluation of Conventional Exposure-Response Analysis Methods: A Small Molecule Cancer Drug Example [_Statistical methodology_]



## Wednesdsay Nov 13


- **(W-003)** 
    - Leveraging Machine Learning and Real-World Data: Time-to-Event Analysis of COVID-19 Patients Using Electronic Health Records [_AI/ML, RWD/RWE_]
- **(W-008)** 
    - The reference corrected VPC (rcVPC) - An informative model diagnostic for assessing underlying exposure-response relationships [_Tools_]
- **(W-032)** 
    - Longitudinal Joint Modeling of Modified Mayo Score and Dropout in Patients with Moderate to Severely Active Ulcerative Colitis [_Statistical Methodology_]
- **(W-045)** 
    - Clinical Trial Simulation to Assess Sample Size and Power For Detecting Differences in Pharmacokinetic Exposure Metrics [_Statistical Methodology_]
- **(W-055)** 
    - Confounding Impact of Event-Driven Exposure Phenomenon on Summary Exposure Metrics in Time-to-Event Exposure Response Analyses [_Statistical Methodology_]
- **(W-069)** 
    - Exploring Appropriate Prior Distributions for Covariance Matrix Estimation in Bayesian Population Pharmacokinetic Analysis [_Bayesian statistics_]
- **(W-084)** 
    - Exploring the feasibility of using AI to identify patient characteristics predictive of histological endpoints in metabolic dysfunction associated steatohepatitis (MASH) [_AI/ML_]
- **(W-099)** 
    - Constructing a virtual control arm and evaluating operating characteristics using TGI metrics to support go/no-go decisions for single-arm Phase Ib/II combination studies [_Virtual control arm_]
- **(W-114)** 
    - Consideration of Study design aspects in the creation of virtual populations for organ impairment studies: One size may not fit all [_Virtual control arm_]
- **(W-133)** 
    - Losing the Forest: Causal Shapley Additive Explanations for Interpretation of Population-Pharmacokinetic models [_Statistical Methodology_]
- **(W-141)** 
    - Disease progression modeling of myositis from real-world data [_RWD/RWE_]



